name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - main  # 当 main 分支有推送时触发部署

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 检查代码
        uses: actions/checkout@v3

      - name: 安装 Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 安装 dependencies
        run: npm install

      - name: 安装 wrangler
        run: npm install -g wrangler

      - name: 部署到 Cloudflare Workers
        env:
          NODE_OPTIONS: --max-old-space-size=4096  # 增加 Node.js 的内存限制
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          wrangler deploy
