name: Deploy to Cloudflare Pages

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Wrangler
        run: npm install -g wrangler

      - name: Check and Create Cloudflare Pages Project
        run: |
          # 检查项目是否存在
          if ! wrangler pages project list | grep -q "grade7-navigation-station"; then
            echo "Creating new Cloudflare Pages project..."
            wrangler pages project create grade7-navigation-station --production-branch=main
            echo "Project created successfully"
          else
            echo "Project already exists"
          fi
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: grade7-navigation-station
          directory: .
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          wranglerVersion: 2
          branch: main
          buildCommand: ""
          buildOutputDirectory: . 